name: XSSeasons
version: '${project.version}'
main: net.xsapi.panat.xsseasons.core.XSSeasons
api-version: 1.19
authors: [ PanatXsectorZ ]
softdepend: [PlaceholderAPI]
description: Seasons for minecraft server
