
database:
  host: localhost
  port: 3306
  dbTable: testdb
  user: root
  password: password

redis:
  enable: false
  host: localhost
  port: 6379
  password: ''

Seasons_sort:
  - "Summer"
  - "Fall"
  - "Spring"
  - "Winter"

World_sync:
  - "syncWorld"
  - "world"

Seasons:
  Summer:
    display: "ฤดูร้อน"
    day_period: 30
  Fall:
    display: "ฤดูฝน"
    day_period: 31
  Spring:
    display: "ฤดูใบไม้ผลิ"
    day_period: 30
  Winter:
    display: "ฤดูหนาว"
    day_period: 31

